import React from 'react';
import {
  Utensils,
  ShoppingBag,
  Car,
  ShoppingCart,
  Zap,
  Film,
  Activity,
  Home,
  TrendingUp,
  Plane,
  Briefcase,
  Sparkles,
  Gift,
  Compass,
  Laptop,
  Building2,
  GraduationCap,
  Coffee,
  Fuel,
  Wifi,
  Smartphone,
  Tv,
  Heart,
  ShieldAlert,
  ShieldCheck,
  Wallet,
  CreditCard,
  Landmark,
  CircleDollarSign,
  Tag,
  PieChart,
  Award,
  Target,
  Trophy,
  Shield,
  Crown,
  Layers,
  Gem,
  Flame,
  Receipt,
  CheckCircle2,
  Users,
  CloudUpload,
} from 'lucide-react';

const ICON_MAP: Record<string, React.ElementType> = {
  Utensils,
  ShoppingBag,
  Car,
  ShoppingCart,
  Zap,
  Film,
  Activity,
  Home,
  TrendingUp,
  Plane,
  Briefcase,
  Sparkles,
  Gift,
  Compass,
  Laptop,
  Building2,
  GraduationCap,
  Coffee,
  Fuel,
  Wifi,
  Smartphone,
  Tv,
  Heart,
  ShieldAlert,
  ShieldCheck,
  Wallet,
  CreditCard,
  Landmark,
  CircleDollarSign,
  Tag,
  PieChart,
  Award,
  Target,
  Trophy,
  Shield,
  Crown,
  Layers,
  Gem,
  Flame,
  Receipt,
  CheckCircle2,
  Users,
  CloudUpload,
};

interface IconRendererProps {
  name: string;
  className?: string;
  size?: number;
}

export const IconRenderer: React.FC<IconRendererProps> = ({ name, className = 'w-5 h-5', size }) => {
  const normalizedKey = name ? (name.charAt(0).toUpperCase() + name.slice(1)) : 'Tag';
  const IconComponent = ICON_MAP[normalizedKey] || ICON_MAP[name] || Tag;

  return <IconComponent className={className} size={size} />;
};
